name: core-v-mini-mcu
channels:
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - cmake
  - ninja
  - cffi
  - ruamel.yaml
  - ruamel.yaml.clib
  - setuptools
  - pip:
    - -r python-requirements.txt
    - -r ../docs/python-requirements.txt